In [3]:
#matplotlib.pylab
import numpy as np
ndarry = np.array(
    [
        [[111,112,113,114],[121,122,123,124],[131,132,134,134]],
        [[211,212,213,214],[221,222,223,224],[231,232,234,234]],
        [[311,312,313,314],[321,322,323,324],[331,332,334,334]],
        [[411,412,413,414],[421,422,423,424],[431,432,434,434]],
    ]
)
print(ndarry.shape)
print(ndarry.ndim)

(4, 3, 4)
3


In [21]:
print(ndarry[0:4,1:3,1:2])

[[[122]
  [132]]

 [[222]
  [232]]

 [[322]
  [332]]

 [[422]
  [432]]]


In [7]:
import pandas as pd
sw = pd.Series([100,200,300,400], index=["Mon","Tue","wed","Thu"])
print(sw>=300)
print(sw[sw>=300])

Mon    False
Tue    False
wed     True
Thu     True
dtype: bool
wed    300
Thu    400
dtype: int64


In [12]:
doc = {"Mon":100,"Tue":200,"Wed":300,"Thu":400}
doc[doc.value>100]

AttributeError: 'dict' object has no attribute 'value'