In [27]:
import os
import numpy as np
dir="images/"
list = os.listdir(dir) # dir is your directory path
number_files = len(list)
print(number_files)

20


In [20]:
onlyfiles = next(os.walk(dir))[2] #dir is your directory path as string
print(len(onlyfiles))

20


In [24]:
path, dirs, files = next(os.walk(dir))
file_count = len(files)
print(file_count)

20


In [95]:
import os
import numpy as np
from PIL import Image as image

def imageToNp(fileName):
    try:
        npArray = np.array(image.open(fileName).resize((200,200)))
        return npArray
    except Exception as e:
        print("Error")
        

dir="photos/"

files = next(os.walk(dir))[2]

file_count = len(files)
imageArray = np.zeros([file_count,200,200,3])

for i,file in enumerate(files):
    imageArray[i] = imageToNp(dir+file)
    
for i in range(len(imageArray)):
    print(imageArray[i])
    print("+================")
    

    

[[[27. 31. 17.]
  [22. 28. 16.]
  [25. 29. 15.]
  ...
  [12. 24. 38.]
  [13. 25. 39.]
  [12. 24. 38.]]

 [[30. 34. 20.]
  [20. 26. 14.]
  [26. 30. 16.]
  ...
  [12. 24. 38.]
  [ 9. 21. 33.]
  [10. 22. 34.]]

 [[27. 31. 17.]
  [24. 30. 18.]
  [24. 28. 14.]
  ...
  [12. 24. 38.]
  [12. 25. 34.]
  [10. 23. 32.]]

 ...

 [[15. 16. 20.]
  [12. 14. 11.]
  [15. 17. 16.]
  ...
  [64. 50. 24.]
  [57. 48. 17.]
  [61. 52. 21.]]

 [[13. 14. 16.]
  [14. 15. 17.]
  [16. 18. 17.]
  ...
  [63. 51. 25.]
  [60. 51. 20.]
  [62. 53. 22.]]

 [[13. 15. 14.]
  [13. 14. 19.]
  [14. 16. 15.]
  ...
  [60. 50. 23.]
  [62. 53. 22.]
  [63. 54. 23.]]]
+================
[[[193.  86.  50.]
  [195.  99.  49.]
  [206. 110.  59.]
  ...
  [178. 102.  86.]
  [186. 113.  94.]
  [195. 125. 100.]]

 [[194.  86.  50.]
  [194.  89.  42.]
  [193.  87.  39.]
  ...
  [176.  99.  81.]
  [202. 127. 106.]
  [188. 118.  93.]]

 [[190.  82.  46.]
  [205. 107.  58.]
  [196.  99.  48.]
  ...
  [181. 102.  87.]
  [183. 110.  93.]
  [181.

In [107]:
import pandas as pd
sw = pd.Series([20,30,20,25,30,40,0], index=["mon","tue","wed","thr","fri","sat","sun"])
sw = sw*2
print(sw[["tue","wed"]])
#print(sw>=300)
#print(sw[sw>=300])

tue    60
wed    40
dtype: int64


In [108]:
import numpy as np
ar = np.array([3,2,4,5,6])
ind = np.array(['a','b','c','d','e'])

obj2 = pd.Series(ar,index=ind)
print(obj2)

a    3
b    2
c    4
d    5
e    6
dtype: int32


In [109]:
sdata = {"Sindh":35000,"Panjab":4500,"KPK":3000,"Balochistan":2000}
tax_by_state = pd.Series(sdata)
print(tax_by_state)
print(tax_by_state.index)

Sindh          35000
Panjab          4500
KPK             3000
Balochistan     2000
dtype: int64
Index(['Sindh', 'Panjab', 'KPK', 'Balochistan'], dtype='object')


In [122]:
sdata = {"Sindh":35000,"Panjab":4500,"KPK":3000,"Balochistan":2000}
tax_by_state = pd.Series(sdata,index=["Panjab","Sindh","KPK","Balochistan","GB"])
tax_by_state["GB"]=15000
#remove(tax_by_state["KPK"])
print(tax_by_state)
print(pd.isnull(tax_by_state))

Panjab          4500.0
Sindh          35000.0
KPK             3000.0
Balochistan     2000.0
GB             15000.0
dtype: float64
Panjab         False
Sindh          False
KPK            False
Balochistan    False
GB             False
dtype: bool


# Pandas DataFrame


In [125]:
import pandas as pd

apples = pd.Series([3,2,0,1])
oranges = pd.Series([3,4,7,8])
list = [3,4,5,6]

data = {"apple":apples,"oranges":oranges,"banana":list}
fruits_df = pd.DataFrame(data)
print(fruits_df)

   apple  oranges  banana
0      3        3       3
1      2        4       4
2      0        7       5
3      1        8       6


In [127]:
import pandas as pd

apples = pd.Series([3,2,0,1],['a','b','c','d'])
oranges = pd.Series([3,4,7,8],index=['e','f','g','h'])
#list = [3,4,5,6]

data = {"apple":apples,"oranges":oranges}
fruits_df = pd.DataFrame(data)
print(fruits_df)

   apple  oranges
a    3.0      NaN
b    2.0      NaN
c    0.0      NaN
d    1.0      NaN
e    NaN      3.0
f    NaN      4.0
g    NaN      7.0
h    NaN      8.0


In [128]:
import pandas as pd

apples = pd.Series([3,2,0,1],['a','b','c','d'])
oranges = pd.Series([3,4,7,8],index=['a','b','c','d'])
#list = [3,4,5,6]

data = {"apple":apples,"oranges":oranges}
fruits_df = pd.DataFrame(data)
print(fruits_df)

   apple  oranges
a      3        3
b      2        4
c      0        7
d      1        8


In [141]:
import pandas as pd

apples = pd.Series([3,2,0,1],['a','b','c','d'],name="Apples")
oranges = pd.Series([3,4,7,8],index=['e','f','g','h'],name="Oranges")
oranges.index = apples.index
#list = [3,4,5,6]

data = {"apple":apples,"oranges":oranges}
#data = [apples,oranges]
fruits_df = pd.DataFrame(data)
print(fruits_df)

   apple  oranges
a      3        3
b      2        4
c      0        7
d      1        8


In [153]:
state = ["Ohio","Ohio","Ohio","Nevada","Nevada","Nevada"]
data = {"state":state,"year":[2000,2001,2002,2004,2003,2005],"pop":[1.5,1.7,3.6,2.4,2.9,3.2]}
state_pop_df = pd.DataFrame(data,index=['Ist','2nd','3rd','4th','5th','6th'])
print(state_pop_df)


      state  year  pop
Ist    Ohio  2000  1.5
2nd    Ohio  2001  1.7
3rd    Ohio  2002  3.6
4th  Nevada  2004  2.4
5th  Nevada  2003  2.9
6th  Nevada  2005  3.2


In [159]:
data['dept']=['a','b','c','d','e','f']
frame2 = pd.DataFrame(data,columns=['year','state','pop','dept'],index=['one','two','three','four','five','six'])
#frame2['dept']=['a','b','c','d','e','f']
frame2.head()


year   state  pop dept
one    2000    Ohio  1.5    a
two    2001    Ohio  1.7    b
three  2002    Ohio  3.6    c
four   2004  Nevada  2.4    d
five   2003  Nevada  2.9    e

In [160]:
frame2["state"]

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [161]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [163]:
frame2.loc["two"]

year     2001
state    Ohio
pop       1.7
dept        b
Name: two, dtype: object

In [164]:
frame2['dept'] = np.arange(len(frame2))
frame2.head()

year   state  pop  dept
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2004  Nevada  2.4     3
five   2003  Nevada  2.9     4