In [1]:
#scrapy
#beautifulsoup
import numpy as np
list = [1,2,3,4]
npList = np.array(list)
npList = npList*2
npList

array([2, 4, 6, 8])

In [10]:
npList = np.zeros(10, dtype=int)
npList = npList+1
npList

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
npList = np.ones(10, dtype=int)
npList

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
npList = np.empty(10,dtype=int)
npList[0]=4


array([4, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
npList = np.ones([10,2],dtype=int)
npList.shape

(10, 2)

In [32]:
npList.reshape(20)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])